#ifndef ORIC_H_INCLUDED
#define ORIC_H_INCLUDED

#define ORICZEROLOWPULSE  208
#define ORICZEROHIGHPULSE 416
#define ORICONEPULSE      208

#define ORICTURBOZEROLOWPULSE  60
#define ORICTURBOZEROHIGHPULSE 470
#define ORICTURBOONEPULSE      60

void tzx_process_blockid_oric();

#endif // ORIC_H_INCLUDED
